services:
  ros2:
    build:
      # Explain this line:
      context: .
      dockerfile: Dockerfile.arm64 # specify 
      args:
        # Must match the Dockerfile
        USERNAME: ros
        USER_UID: 1000
        USER_GID: 1000
    image: ros2-lyrical-arm64:latest
    container_name: ros2-workspace
    # GUI and permission
    network_mode: host 
    ipc: host
    pid: host
    stdin_open: true
    privileged: true
    tty: true
    # Placed inside the user's home directory
    working_dir: /home/ros/ws
    user: ros

    environment:
      - ROS_DOMAIN_ID=42
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      # Fix bug
      - GPIOZERO_PIN_FACTORY=lgpio
      - RPI_LGPIO_CHIP=0

    volumes:
      # Named volume keeps build, install, and log files cached and fast
      - workspace_cache:/home/ros/ws
      # My live code source maps on top
      - ./source:/home/ros/ws/src

      # map devices 
      - /dev:/dev
    
    device_cgroup_rules:
      - 'c *:* rmw'
    
    
    command: /bin/bash

volumes:
  workspace_cache: