# docker-compose.gh-cache.yml
services:
  laptop_dev:
    build:
      cache_from: ["type=gha,scope=laptop_dev"]
      cache_to: ["type=gha,mode=max,scope=laptop_dev"]

  controller:
    build:
      cache_from: ["type=gha,scope=controller"]
      cache_to: ["type=gha,mode=max,scope=controller"]

  robot_prod:
    build:
      cache_from: ["type=gha,scope=robot_prod"]
      cache_to: ["type=gha,mode=max,scope=robot_prod"]
