FROM ros:lyrical-ros-base

RUN apt-get update \
    && apt-get install -y nano \
    && rm -rf /var/lib/apt/lists/*

# COPY config/ /site_config/
# TODO: Remove the rm -rf lines?
# Create a non-root user. Note that the username is different from host!
ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Delete user if it exists in container (e.g Ubuntu Noble: ubuntu)
RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi

RUN groupadd --gid $USER_GID $USERNAME \
    # -s specifies the default login shell for the user
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
    # Create a home directory and config directory for the user (some programs want that)
    && mkdir /home/$USERNAME/.config && chown $USER_UID:$USER_GID /home/$USERNAME/.config


# [Optional] Add sudo support. Omit if you don't need to install software after connecting.
RUN apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && rm -rf /var/lib/apt/lists/*

# Add pip and lgpio to Pi Dockerfile
RUN apt-get update && apt-get install -y \
    python3-pip \
    swig \
    python3-dev \
    build-essential \
    liblgpio-dev \
    # Break system packages required for global install
    && pip3 install gpiozero lgpio --break-system-packages \
    && rm -rf /var/lib/apt/lists/*

# Install demo_nodes for testing
RUN apt-get update \
    && apt-get install -y ros-lyrical-demo-nodes-cpp \
    && rm -rf /var/lib/apt/lists/*

# Install Cyclone DDS and networking debug tools (ping, ip)
RUN apt-get update \
    && apt-get install -y ros-lyrical-rmw-cyclonedds-cpp \
    iproute2 \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*


# Tell ROS 2 to use Cyclone as the default middleware
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

# Force Cyclone to Wi-Fi using modern syntax
# Hardcoded to point directly at the Laptop
COPY cyclonedds_pi.xml /cyclonedds.xml
ENV CYCLONEDDS_URI="file:///cyclonedds.xml"

# --- ADD THIS BLOCK FOR ROSDEP ---
WORKDIR /home/ros/ws

# Copy your host's 'source' folder into the container's 'src' folder for the build phase
COPY ./source ./src

# Initialize and update rosdep
RUN rosdep init || true \
    && rosdep update

# Install dependencies based on the package.xml files in the copied src/ folder
RUN apt-get update \
    && rosdep install -y --ignore-src -r \
    # Only install from those that are needed for server
        --from-paths src/my_bringup src/motor_driver_py src/realsense-ros \
       --skip-keys "slam_toolbox \
                    turtlebot3_gazebo \
                    gazebo_ros_pkgs \
                    ros_gz \
                    ros_gz_sim \
                    ros_gz_bridge \
                    rviz2 \
                    teleop_twist_keyboard \
                    teleop_twist_joy \
                    python3-gpiozero \
                    python3-lgpio" \
    && rm -rf /var/lib/apt/lists/*
# ---------------------------------

COPY entrypoint.sh /entrypoint.sh
# If we were using a base image, we would you the locale setting as well.


ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
CMD ["/bin/bash"]

# Source the ROS2 environment! Working!
RUN echo "source /opt/ros/lyrical/setup.bash" >> /home/ros/.bashrc

# Set the default user. Omit if we want to keep the default as root
# USER $USERNAME
