x-device-access: &device-access
  device_cgroup_rules:
    # Device cgroup rule (string that has the device type 'c for character', major id 13 for all inputdevicse, then minor id (* for all))
    - 'c *:* rmw'

# Common ROS networking settings
x-ros-net: &ros-net
  network_mode: host
  ipc: host
  pid: host

# Common build args (must match Dockerfile ARGs)
x-build-args: &build-args
  USERNAME: ros
  USER_UID: 1000
  USER_GID: 1000

services:
  laptop_dev:
    build:
      context: .
      args: *build-args
      # Which dockerfile section to use
      target: laptop_dev

    image: ros2-laptop-dev:latest
    <<: [*ros-net, *device-access]
    stdin_open: true
    privileged: true # Needed for PIO access
    tty: true
    # Placed inside the user's home directory
    working_dir: /home/ros/ws
    user: ros

    environment:
      - ROS_DOMAIN_ID=42
      # For linux native: Just use 0 for display
      # For windows -in-linux(example: Hyper-V): Use host.docker.internal:0.0
      - DISPLAY=host.docker.internal:0.0
      # Tell X11 where to find auth cookie
      - XAUTHORITY=/home/ros/.Xauthority
      - QT_X11_NO_MITSHM=1

    volumes:
      - /dev:/dev
      # Named volume keeps build, install, and log files cached and fast
      # FIX: Cache only the sub-folders, leaving /home/ros/ws root untouched
      - laptop_build:/home/ros/ws/build
      - laptop_install:/home/ros/ws/install
      - laptop_log:/home/ros/ws/log
      # My live code source maps on top
      - ./source:/home/ros/ws/src
      # Share the GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # MAP THE COOKIE: Mounts your host login's display permission token straight to the ros user's home folder
      - ~/.Xauthority:/home/ros/.Xauthority:ro

  # Controller (operator-side dev)
  controller_dev:
    build:
      context: .
      args: *build-args
      # Which dockerfile section to use
      target: controller_dev

    image: ros2-controller_dev:latest
    <<: [*ros-net, *device-access]
    stdin_open: true
    privileged: true # Needed for PIO access
    tty: true
    # Placed inside the user's home directory
    working_dir: /home/ros/ws
    user: ros

    environment:
      - ROS_DOMAIN_ID=42
      # Fix bug
      - GPIOZERO_PIN_FACTORY=lgpio
      - RPI_LGPIO_CHIP=0
      - DISPLAY=${DISPLAY:-:0}
      # Tell X11 where to find auth cookie
      - XAUTHORITY=/home/ros/.Xauthority
      - QT_X11_NO_MITSHM=1

    volumes:
      - /dev:/dev
      # Named volume keeps build, install, and log files cached and fast
      # FIX: Cache only the sub-folders, leaving /home/ros/ws root untouched
      - controller_build:/home/ros/ws/build
      - controller_install:/home/ros/ws/install
      - controller_log:/home/ros/ws/log
      # My live code source maps on top
      - ./source:/home/ros/ws/src
      # Share the GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # MAP THE COOKIE: Mounts your host login's display permission token straight to the ros user's home folder
      - ~/.Xauthority:/home/ros/.Xauthority:ro

  # For simulating the robot
  robot_sim:
    build:
      context: .
      args: *build-args
      target: robot_dev # reuse the existing image, no new stage needed
    image: ros2-robot_dev:latest
    <<: *ros-net # keep DDS networking consistent with real robot_dev
    stdin_open: true
    tty: true
    working_dir: /home/ros/ws
    user: ros
    environment:
      - ROS_DOMAIN_ID=42
      - GPIOZERO_PIN_FACTORY=mock # <- the key change: no real GPIO chip needed
      - DISPLAY=${DISPLAY:-:0} # for RViz2 / rqt if you visualize later
    volumes:
      - robot_build:/home/ros/ws/build
      - robot_install:/home/ros/ws/install
      - robot_log:/home/ros/ws/log
      - ./source:/home/ros/ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/ros/.Xauthority:ro

  robot_dev:
    build:
      context: .
      args: *build-args

      target: robot_dev

    image: ros2-robot_dev:latest
    # GUI and permission
    <<: [*ros-net, *device-access]
    stdin_open: true
    tty: true
    # Placed inside the user's home directory
    working_dir: /home/ros/ws
    privileged: true
    user: ros

    # Add gpio group for gpiozero access
    group_add:
      - '986' # For gpio access
      - '44' # For camera access

    environment:
      - ROS_DOMAIN_ID=42
      - GPIOZERO_PIN_FACTORY=lgpio
      - RPI_LGPIO_CHIP=0
      - DISPLAY=${DISPLAY:-:0}
      # For camera
      - UDEV=1

    volumes:
      # Named volume keeps build, install, and log files cached and fast
      # Cache build/ install/ log/ as named volumes, but NEVER mount a named volume over ~/ws/src, it shadows the ./source bind mount with stale/empty content.
      - robot_build:/home/ros/ws/build
      - robot_install:/home/ros/ws/install
      - robot_log:/home/ros/ws/log
      # For camera access
      - /dev:/dev
      - /run/udev:/run/udev
      - /run/dbus:/run/dbus

      # My live code source maps on top
      - ./source:/home/ros/ws/src

  robot_prod:
    build:
      context: .
      args: *build-args

      target: robot_prod

    image: ros2-robot_prod:latest
    # GUI and permission
    <<: [*ros-net, *device-access]
    stdin_open: true
    tty: true
    group_add:
      - '986' # For gpio access
      - '44' # For camera

    # Placed inside the user's home directory
    working_dir: /home/ros/ws
    privileged: true
    user: ros
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=42
      - GPIOZERO_PIN_FACTORY=lgpio
      - RPI_LGPIO_CHIP=0
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      # No caches here, everything is built in the dockerfile
      - /dev:/dev
      # For camera access
      - /run/udev:/run/udev
      - /run/dbus:/run/dbus

volumes:
  controller_build:
  controller_install:
  controller_log:
  # Cache
  robot_build:
  robot_install:
  robot_log:
  laptop_build:
  laptop_install:
  laptop_log:
