name: Test Docker Builds
# Gh-actions caching: https://www.blacksmith.sh/blog/cache-is-king-a-guide-for-docker-layer-caching-in-github-actions
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
        # 1. Download your code so the runner can see your root Dockerfile
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Convert repository name to lowercase for GitHub Registry
      - name: Lowercase Repository Name
        id: repo
        run: echo "name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

        # 3. Log into GitHub's built-in container registry
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Uses your GitHub username automatically
          password: ${{ secrets.GITHUB_TOKEN }} # Generated automatically by GitHub

      # 1. Set up Docker Buildx (required for 'gha' caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    # Build laptop_dev target
      - name: Build 'laptop_dev' docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          target: laptop_dev
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.name }}:laptop_dev
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.name }}:cache-laptop_dev
          cache-to: type=registry,ref=ghcr.io/${{ steps.repo.outputs.name }}:cache-laptop_dev,mode=max

      - name: Build 'controller' docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          target: controller
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.name }}:controller
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.name }}:cache-controller
          cache-to: type=registry,ref=ghcr.io/${{ steps.repo.outputs.name }}:cache-controller,mode=max
      
      - name: Build 'robot_prod' docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          target: robot_prod
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.name }}:robot_prod`
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.name }}:cache-robot_prod
          cache-to: type=registry,ref=ghcr.io/${{ steps.repo.outputs.name }}:cache-robot_prod,mode=max
    