name: Test Docker Builds
# Gh-actions caching: https://www.blacksmith.sh/blog/cache-is-king-a-guide-for-docker-layer-caching-in-github-actions
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
        # 1. Log into GitHub's built-in container registry
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Uses your GitHub username automatically
          password: ${{ secrets.GITHUB_TOKEN }} # Generated automatically by GitHub

      # 1. Set up Docker Buildx (required for 'gha' caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: user/app:latest
          cache-from: type=registry,ref=user/app:buildcache
          cache-to: type=registry,ref=user/app:buildcache,mode=max

      - name: Test Build 'laptop_dev' target
        # The -f flags merge your base compose with the GitHub caching rules
        run: docker compose -f docker-compose.yml -f docker-compose.gh-cache.yml build laptop_dev
        env:
          BUILDX_NO_DEFAULT_LOAD: 1

      - name: Test Build 'controller' target
        run: docker compose -f docker-compose.yml -f docker-compose.gh-cache.yml build controller
        env:
          BUILDX_NO_DEFAULT_LOAD: 1

      - name: Test Build 'robot' target (Production)
        run: docker compose -f docker-compose.yml -f docker-compose.gh-cache.yml build robot_prod
        env:
          BUILDX_NO_DEFAULT_LOAD: 1
