name: Test Docker Builds
# Gh-actions caching: https://www.blacksmith.sh/blog/cache-is-king-a-guide-for-docker-layer-caching-in-github-actions
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      # ADD MORE TARGETS/EDIT here!
        target: [laptop_dev, controller_dev, robot_prod, robot_dev]
    steps:
        # 1. Download your code so the runner can see your root Dockerfile
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Convert repository name to lowercase for GitHub Registry
      - name: Lowercase Repository Name
        id: repo
        run: echo "name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

        # 3. Log into GitHub's built-in container registry
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Uses your GitHub username automatically
          password: ${{ secrets.GITHUB_TOKEN }} # Generated automatically by GitHub

      # 1. Set up Docker Buildx (required for 'gha' caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    # Build laptop_dev target
      - name: Build and push docker target
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          target: ${{ matrix.target }}
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.name }}:${{matrix.target}}
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.name }}:cache-${{matrix.target}}
          cache-to: type=registry,ref=ghcr.io/${{ steps.repo.outputs.name }}:cache-${{matrix.target}},mode=max